#!/bin/bash
##### These lines are for Moab
#MSUB -l nodes=1
#MSUB -l partition=quartz
#MSUB -l walltime=00:12:00
#MSUB -q pbatch
######MSUB -l ttc=10
#MSUB -A optimiz
#MSUB -V

##### Launch parallel job using srun
for n in 1 2 4 8 16 32
do
    printf 'Running with %.d processors \n' $n
    start=`date +%s%N`
    srun -n $n singularity exec mpich.simg /opt/vecdot
    end=`date +%s%N`
    printf 'Time singularity: %.10f \n' $(((end-start)/1000000))
    start=`date +%s%N`
    srun -n $n ./vecdot
    end=`date +%s%N`
    printf 'Time mpi: %.10f \n' $(((end-start)/1000000))
done
